# Basic Server Settings
listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Security & Isolation
chroot_local_user=YES
allow_writeable_chroot=YES

# Passive Mode Settings for Docker Networking
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=127.0.0.1

# Logging & Directory Settings
xferlog_enable=YES
dscr_default_time=300